search functionality
I-TECH-UW/OpenELIS-Global-2 pull request #1072
Opened 2024-06-06 06:50 UTC by Isabirye1515

[Screencast from 06-06-24 09:39:29.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/150329678/baf02944-b254-4ea8-83c4-422cd6cddd12)
![Screenshot from 2024-06-06 09-49-03](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/150329678/461d6cfb-5d10-4ef4-9907-bb8acdc0e084)

2024-06-10 17:33 UTC, mozzy11 commented
Thanks @Isabirye1515 .
Can you add a screen recording ??

2024-06-11 07:33 UTC, Isabirye1515 commented
[Screencast from 11-06-24 10:28:05.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/150329678/e2c98f22-681e-48ce-b67b-7c7c82c6faed)

2024-06-12 08:27 UTC, josephbate commented
well done @Isabirye1515

2024-06-12 09:41 UTC, Isabirye1515 commented
thanks bro @josephbate and Mr @mozzy11

2024-06-12 10:35 UTC, mozzy11 requested changes
Thanks @Isabirye1515 for attemting to do this.
I like the search results bar you have implemeneted
This search button should only suport patient search

- by first name , 
 - last name, 
 - National Id
 - Patient ID
 - Unique Health Id
 - Date Of Birth. 
 
 The serach Results should be Autocomplete where by matching results are displayed as user is typing

2024-06-12 10:50 UTC, mozzy11 commented on frontend/src/components/layout/search/searchBar.js
> +    if (isAccessionNumber) {
fo the start, lets implement only Patient Search

2024-06-12 10:51 UTC, mozzy11 commented on frontend/src/components/Style.css
> +.patientHeader{
you need to run `npm run format `to properly fromat your frontend code

2024-06-12 13:44 UTC, Isabirye1515 commented
Ok thank sir

2024-06-16 16:42 UTC, Isabirye1515 commented
[Screencast from 16-06-24 03:02:05.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/150329678/57bfe377-fcfc-4713-896a-32a1da7c980b)

2024-06-19 09:42 UTC, closed without merging