Add more PersonServiceTest-#902
I-TECH-UW/OpenELIS-Global-2 pull request #1089
Opened 2024-06-11 15:03 UTC by Agaba-derrick

# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes confirm to the OpenElis Global x3 Styleguide and design documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary
Added at least 90% of the PersonService Test
## Screenshots
![Screenshot from 2024-06-11 17-37-41](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/79217378/a26986f8-4906-496f-a19c-423f15e372b3)

## Related Issue

 Add more integration tests to the Patient and Person service #902 

## Other
@mozzy11 kindly Requesting for Review here

2024-06-11 18:29 UTC, mherman22 requested changes
Thanks @Agaba-derrick  for this, it generally LGTM,

please add tests for https://github.com/mherman22/OpenELIS-Global-2/blob/564de765f77329a9c3d54c588d03f2a47130ca2c/src/main/java/org/openelisglobal/person/service/PersonServiceImpl.java#L59-L69 aswell

2024-06-11 18:29 UTC, mherman22 commented on src/test/java/org/openelisglobal/person/PersonServiceTest.java
> +        // Assert.assertEquals(1, personService.getAllPersons().size());
i think we dont need this, you can remove it

2024-06-11 18:29 UTC, mherman22 commented on src/test/java/org/openelisglobal/person/PersonServiceTest.java
> +        System.out.println("Creating person with details: " + person);
we dont need these

2024-06-12 09:33 UTC, mozzy11 commented on src/main/java/org/openelisglobal/person/daoimpl/PersonDAOImpl.java
> -            query.setParameter("personId", Integer.parseInt(personId));
why this change ??

2024-06-13 10:31 UTC, Agaba-derrick commented
> Thanks @Agaba-derrick for this, it generally LGTM,
> 
> please add tests for https://github.com/mherman22/OpenELIS-Global-2/blob/564de765f77329a9c3d54c588d03f2a47130ca2c/src/main/java/org/openelisglobal/person/service/PersonServiceImpl.java#L59-L69 aswell

added

2024-07-03 10:47 UTC, closed without merging