Fix rewriting test management config menu page
I-TECH-UW/OpenELIS-Global-2 pull request #1215
Opened 2024-08-01 22:15 UTC by adityadeshlahre

- referencing #1051 

- Fixes #1146 

## WIP

### Converting All pages pages/sub-pages of Test Management Config Menu 

- [ ] Main page (initialization done) which will render all the sub management pages 

### Spelling corrections
- [ ] Rename existing test names
- [ ] Rename Existing Panels
- [ ] Rename Existing Test Sections
- [ ] Rename Existing Unit of Measure Entries
- [ ] Rename existing result list options
- [ ] Rename existing method names

### Test Organization
- [x] View Test Catalog (done already)
- [ ] Manage Methods
- [ ] Add new tests
- [ ] Modify tests
- [ ] Activate/Deactivate tests
- [ ] Enable/disable test orderability.
- [ ] Manage Test Units
- [ ] Manage Sample Types
- [ ] Manage Units of Measure
- [ ] Manage Panels
- [ ] Add result select list
- [ ] Manage Testing Algorithms and Reflex tests

## These are all the pages which are required to create eventually I will try to complete this in this PR

I will keep posting workflow of pages when it would be functional 

Thank you :slightly_smiling_face:

2024-08-10 18:15 UTC, adityadeshlahre commented
### Route Page DONE (testManagementConfigPage)
`https://localhost/admin#TestRenameEntry`

#### WorkFlow VIDEO
![testRenamePostRequestWorking](https://github.com/user-attachments/assets/a32a0841-b60e-4c6a-9093-ab55477f3383)

2024-08-14 15:27 UTC, adityadeshlahre commented
## Panel Rename Route Done

```
https://localhost/admin#PanelRenameEntry
```

### WorkFlow Done
![panelRenameEntryDone](https://github.com/user-attachments/assets/71a85aaa-cc37-4962-b83d-09340ec039d9)

2024-12-16 11:52 UTC, mozzy11 commented on frontend/src/components/admin/testManagementConfigMenu/TestManagementConfigMenu.js
> +                  //   window.location.assign("/admin#TestModifyEntry");
in the case when the component doesnt exist or not functional in React , just link to the old JSP page ie `api/OpenELIS-Global/TestModifyEntry`

2024-12-16 11:54 UTC, mozzy11 requested changes
Thanks @adityadeshlahre .
When the on the  component on the Test management is not yet complete in the new React UI , just link to the old JSP page components

2024-12-16 14:42 UTC, mozzy11 commented
Thanks @adityadeshlahre 
Can you add a new screen recording of the new changes ??

2024-12-16 15:55 UTC, adityadeshlahre commented
> Thanks @adityadeshlahre Can you add a new screen recording of the new changes ??

## Update Video of on click workflow

https://github.com/user-attachments/assets/ae78a075-e316-4e16-8a82-c9bb5c05d2d5

2024-12-16 17:18 UTC, mozzy11 commented
Hello @adityadeshlahre . 
Ive tried using the rename components but they dont seem to work.
Can you fix that ??

2024-12-16 17:53 UTC, adityadeshlahre commented
> Hello @adityadeshlahre . Ive tried using the rename components but they dont seem to work. Can you fix that ??

@mozzy11 doubled checked everything is working attaching a video 


https://github.com/user-attachments/assets/8fbe866e-244b-4c95-89a3-d449694af8a8

2024-12-23 07:04 UTC, mozzy11 requested changes
Hello @adityadeshlahre ,
Ive tested the latest fix but its not working yet.
Can you first test your PR on a clean enviroment like gitpod ??

2025-01-29 10:43 UTC, mozzy11 commented
Hello @adityadeshlahre , thanks for the great work

2025-01-29 11:05 UTC, merged