Add tests for MenuService
I-TECH-UW/OpenELIS-Global-2 pull request #1217
Opened 2024-08-02 12:02 UTC by Agaba-derrick

# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes confirm the OpenElis Global x3 Styleguide and design
      documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary

## Screenshots
![Screenshot from 2024-08-02 11-20-27](https://github.com/user-attachments/assets/9d8a3b4d-301c-4c40-8b80-c038d1fd250e)

## Related Issue
Add intergration Tests for menu #1216
## Other

@mozzy11 kindly review this

2024-08-02 13:55 UTC, mherman22 reviewed
@Agaba-derrick please run `mvn spotless:apply` to fix the formatting of this PR and fix the failing build

2024-08-03 19:19 UTC, Agaba-derrick commented
![Screenshot from 2024-08-03 22-14-43](https://github.com/user-attachments/assets/247564f3-0d8d-42f8-b4b9-65176cd8482d)

2024-08-04 08:26 UTC, mherman22 requested changes
@Agaba-derrick try to align your test methods to some of the suggestions i have added otherwise this looks fine already

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testSetGetHideInOldUI() {
```suggestion
    public void setGetHideInOldUI_shouldSetHideInOldUI() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testGetSetParent() {
```suggestion
    public void getSetParent_shouldGetTheSetParentMenu() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testSaveSingleMenuItem() {
```suggestion
    public void save_shouldSaveTheSingleMenuItem() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testSaveMultipleMenuItems() {
```suggestion
    public void save_shouldSaveMultipleMenuItems() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testGetAllActiveMenus() {
```suggestion
    public void getAllActiveMenus_shouldGetAllActiveMenus() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testGetSetAdminMenuItems() {
```suggestion
    public void getSetAdminMenuItems_shouldGetTheSetAdminMenuItems() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +import static org.junit.Assert.*;
Lets try to avoid wild cards here

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testGetSetTotalRecordCount() {
```suggestion
    public void getTotalRecordCount_shouldGetSetTotalRecordCount() {
```

2024-08-04 08:26 UTC, mherman22 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void testGetSetFromRecordCount() {
```suggestion
    public void getFromRecordCount_shouldGetSetFromRecordCount() {
```

2024-08-04 17:23 UTC, mherman22 approved these changes
LGTM 👍🏿 

cc: @mozzy11

2024-08-05 12:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +        AdminMenuForm form = new AdminMenuForm();
This is not an intergration test for the Menu Service

2024-08-05 12:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void setToRecordCount_shouldSetAndReturnToRecordCount() {
This is not an intergration test for the Menu Service

2024-08-05 12:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void setPresentationOrder_shouldSetAndReturnPresentationOrder() {
This is not an intergration test for the Menu Service

2024-08-05 12:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void setElementId_shouldSetAndReturnElementId() {
This is not an intergration test for the Menu Service

2024-08-05 12:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +    public void setActionURL_shouldSetAndReturnActionURL() {
This is not an intergration test for the Menu Service

2024-08-05 15:18 UTC, Agaba-derrick commented
@mozzy11  i notice that even after running maven spotless:apply the CI builds still fail !!

2024-08-22 14:19 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +        Assert.assertEquals("100", form.getTotalRecordCount());
This is not an intergration Test

2024-08-22 14:20 UTC, mozzy11 requested changes
Thanks @Agaba-derrick for the PR.
Can you remove all the methods that dont test the MenuService ??

2024-08-22 14:20 UTC, mozzy11 commented on src/test/java/org/openelisglobal/menu/MenuServiceTest.java
> +        Menu menu = new Menu();
This is not an intergration Test

2024-08-28 22:29 UTC, Agaba-derrick commented
> Thanks @Agaba-derrick for the PR. Can you remove all the methods that dont test the MenuService ??
 yes sure

2025-01-30 07:26 UTC, mozzy11 requested changes
@Agaba-derrick can we also use datasets for this test too ??

2025-02-03 06:38 UTC, closed without merging