Patient Status CSV Report
I-TECH-UW/OpenELIS-Global-2 pull request #1265
Opened 2024-09-16 18:21 UTC by pascagihozo

# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Summary

This PR is to introduce the CSV downloading functionality in OpenElis at Patient Status Report which was initially generating information in pdf but the users would like to have information in CSV as well to facilitate them in making statistical decisions. New class CSVPatientStatusReport and CSVPatientStatusReportColumn builder were created which copies the same mechanisms as CSVSampleRejectionReport and its column builder. The feature is patially working on my side i.e the endpoint is tested to be working( status 200) and the issue is that instead of receiving the CSV of patient data we are receiving html content in CSV file. Additionally the CSV Patient Status Report was not modified to have the sql querires that picks the data that is specific to the Patient Status Report so further help on writing SQL queries is beneficial as well. Please review the PR and help out @adityadeshlahre @mozzy11 @caseyi 

## Screenshots

[Screencast from 2024-09-16 22-19-47.webm](https://github.com/user-attachments/assets/96efaf56-08ed-42bb-93f0-d390dd4f4660)

## Related Issue

[Add a link to the related issue or mention it here if applicable]

## Other

[Add any additional information or notes here]

2024-09-17 07:05 UTC, mozzy11 commented
can you run `mvn spotless:apply` to format your changes

2024-09-17 10:46 UTC, mozzy11 commented
Thanks @pascagihozo .
The screen recording does not seem to be clear , can you attach a clear screen record or sample of the report generated ??

2024-09-17 11:19 UTC, pascagihozo commented
[PatientStatusReport (6).csv](https://github.com/user-attachments/files/17027302/PatientStatusReport.6.csv)
[Screencast from 2024-09-17 15-14-53.webm](https://github.com/user-attachments/assets/686d574a-072e-4f83-9a9b-2f3d13208a31)


Hello @mozzy11 

Please find the file generated and video capture of the Console &Network above

Thank you!

2024-09-23 12:29 UTC, mozzy11 commented on src/main/java/org/openelisglobal/qaevent/controller/RejectionController.java
> +    @RequestMapping(value = "/patientStatus", method = RequestMethod.GET)
you dont need a new endpoint for handling the report

2024-09-23 12:33 UTC, mozzy11 commented on frontend/src/components/reports/common/PatientStatusReport.js
> +  // function to handle csv report start
this may not be needed . we only need to change the report type param

2024-09-23 12:34 UTC, mozzy11 commented on frontend/src/components/reports/common/PatientStatusReport.js
> +                  <Column lg={16} md={8} sm={4}>
this should only display for a specific report type ie `CSVPatientStatusReport`

2024-09-23 12:35 UTC, mozzy11 commented on frontend/package.json
> -    "prettier": "^3.3.2",
can you discard these, you can add them in a separate PR

2024-09-23 12:35 UTC, mozzy11 commented on frontend/package-lock.json
> +        "prettier": "^3.3.3",
can you discard these changes ?? you can create a separate PR for this

2024-09-23 12:43 UTC, mozzy11 commented on frontend/src/components/reports/common/PatientStatusReport.js
> +  // function to handle csv report start
you just need add a link in the report menu in this [component](https://github.com/pascagihozo/OpenELIS-Global-2-UNDP/blob/develop/frontend/src/components/reports/Routine.js#L13)
ie 

 ```
{
      title: <FormattedMessage id="sidenav.title.statusreport.csv" />,
      icon: IbmWatsonDiscovery,
      SideNavMenuItem: [
        {
          link: "/RoutineReport?type=patient&report=CSVPatientStatusReport",
          label: <FormattedMessage id="sidenav.label.statusreport.csv" />,
        },
      ],
    },
```


then add  report component [here ](https://github.com/pascagihozo/OpenELIS-Global-2-UNDP/blob/develop/frontend/src/components/reports/routine/Index.js#L13)

ie 
 {type === "patient" && report === "CSVPatientStatusReport" && (
        <PatientStatusReport
          report={"CSVPatientStatusReport"}
          id={"openreports.patientTestStatus.csv"}
        />
      )}

2024-09-23 12:43 UTC, mozzy11 commented on src/main/java/org/openelisglobal/reports/action/implementation/ReportImplementationFactory.java
> +            } else if (report.equals("patientReport")) {
you should use a consistent report param here ie  `CSVPatientStatusReport`

2024-09-23 12:45 UTC, mozzy11 commented on src/main/java/org/openelisglobal/reports/action/implementation/reportBeans/CSVColumnBuilder.java
> +//    public abstract String[] getHeaders();
you can remove unused comented code

2024-09-23 12:51 UTC, mozzy11 requested changes
Thanks @pascagihozo for attempting to work on this report.
In general you can get rid of the new endpoint you created ie `/patientStatus` and use the existing endpoint `/reportPrint`. And also see other comments.

2024-12-10 06:54 UTC, closed without merging