Refactored the getSysUserId Method into a Single Class
I-TECH-UW/OpenELIS-Global-2 pull request #1303
Opened 2024-11-08 15:39 UTC by Ariho-Seth

# Pull Requests Requirements

- [X] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [X] The PR includes a video showing the changes for the work done.
- [X] The PR title follows conventional commit label standards.
- [X] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [X] The changes include tests or are validated by existing tests.
- [X] I have read and agree to the Contributing Guidelines of this project.

## Summary

## Screenshots

![VsCode](https://github.com/user-attachments/assets/ed841ca6-4269-4b90-a169-fa1fe8132dec)

## [Refactor getSysUserId into a Separate Class ](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1222)

https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1222

## Other

Created a new class ie **ControllerUtills** and moved the `protected String getSysUserId ` method into the new class. Then refactored all the classes that were initialy extending the BaseRestController to extend the **ControllerUtills** class

2024-11-12 11:23 UTC, mozzy11 requested changes
Thanks @Ariho-Seth for attempting this.

You need only to create a new Class  `ControllerUtills ` under  the [util ](https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/develop/src/main/java/org/openelisglobal/common/util) and move the getSysUserId there . we would add more commnUtils there

The ControllerUtills Class shoudnt implement IActionConstants . Leave it for or the  [BaseController](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/java/org/openelisglobal/common/controller/BaseController.java) 

Then let the [BaseController](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/java/org/openelisglobal/common/controller/BaseController.java)  and [BaseRestController](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/java/org/openelisglobal/common/rest/BaseRestController.java) Classes that extend ControllerUtills .

The Rest of the controller Classes should only Extend `BaseController` or `BaseRestController ` accordingly.

2024-11-19 10:09 UTC, Ariho-Seth commented
Hello @mozzy11 , please checkout that and tell me whether the solution is okay now! Thanks

2024-11-19 11:38 UTC, mozzy11 commented on src/main/java/org/openelisglobal/qaevent/controller/rest/ViewNonConformEventsRestController.java
> +public class ViewNonConformEventsRestController extends ControllerUtills {
This is a Rest Controller oler so it  should  extend  the` BaseRestController` instead

2024-11-19 11:40 UTC, mozzy11 commented on src/main/java/org/openelisglobal/qaevent/controller/rest/ReportNonConformEventsRestController.java
> +public class ReportNonConformEventsRestController extends ControllerUtills {
This is a Rest Controller oler so it  should  extend  the` BaseRestController` instead

2024-11-19 11:40 UTC, mozzy11 commented on src/main/java/org/openelisglobal/qaevent/controller/rest/NonConformingEventsCorrectionActionRestController.java
> +public class NonConformingEventsCorrectionActionRestController extends ControllerUtills {
This is a Rest Controller oler so it  should  extend  the` BaseRestController` instead

2024-11-19 11:40 UTC, mozzy11 commented on src/main/java/org/openelisglobal/notifications/rest/NotificationRestController.java
> +public class NotificationRestController extends ControllerUtills {
This is a Rest Controller oler so it  should  extend  the` BaseRestController` instead

2024-11-19 11:47 UTC, mozzy11 commented on src/main/java/org/openelisglobal/common/util/ControllerUtills.java
> +    private static final String USER_SESSION_DATA = "userSessionData";
you dont need to declare this variable again just import it

2024-11-19 11:48 UTC, mozzy11 commented on src/main/java/org/openelisglobal/common/util/ControllerUtills.java
> +        UserSessionData usd = (UserSessionData) request.getSession().getAttribute(USER_SESSION_DATA);
just import this as `IActionConstants.USER_SESSION_DATA`

2024-11-26 20:24 UTC, Ariho-Seth commented
Hello @mozzy11 I added the requested changes, Is it now good to go?

2025-01-08 16:59 UTC, mozzy11 commented
Thanks @Ariho-Seth

2025-01-08 16:59 UTC, mozzy11 approved these changes

2025-01-08 17:32 UTC, merged