Add-noteservice-Tests
I-TECH-UW/OpenELIS-Global-2 pull request #1309
Opened 2024-11-17 11:02 UTC by Agaba-derrick

# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary
Added the note Service Tests
## Screenshots
![Screenshot from 2024-11-17 13-55-29](https://github.com/user-attachments/assets/4e5f7cc5-542e-4f52-9589-5e4f165c06b7)

## Related Issue
 Add Intergration Service tests #1224 
## Other
@mozzy11 @mherman22  if this makes sense we could add more methods here

2024-11-17 18:15 UTC, mherman22 requested changes
Nice!

Please add all tests from the service methods at https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/94630dfa4be418553d527e796170a11491b1d444/src/main/java/org/openelisglobal/note/service/NoteServiceImpl.java#L97-L440

2025-01-09 18:57 UTC, Agaba-derrick commented
@mozzy11 any hint on why this is likely printing out an empty this list?
![Screenshot from 2025-01-09 21-55-20](https://github.com/user-attachments/assets/76a18222-fc1c-4d59-95b3-ddb0aa135b2b)

2025-01-30 07:16 UTC, mozzy11 commented on src/test/java/org/openelisglobal/note/NoteServiceTest.java
> +        String noteId = noteService.insert(note);
use the datasets to insert any test data

2025-01-30 07:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/note/NoteServiceTest.java
> +        noteService.insert(note2);
use the datasets to insert test data

2025-01-30 07:17 UTC, mozzy11 commented on src/test/java/org/openelisglobal/note/NoteServiceTest.java
> +        noteService.insert(note2);
use datasets

2025-02-05 15:31 UTC, mozzy11 commented
Thanks  @Agaba-derrick .
can you fix the format issues and also work on the review comments ??

2025-02-05 15:33 UTC, Agaba-derrick commented
yea sure working on it 

> Thanks @Agaba-derrick . can you fix the format issues and also work on the review comments ??

yea sure working on it  ASAP

2025-02-11 08:30 UTC, mozzy11 commented on src/test/java/org/openelisglobal/note/NoteServiceTest.java
> +            user = new SystemUser();
Can you use dataset to create the user object ??

2025-02-17 13:18 UTC, josephbate commented
Hello @Agaba-derrick can you format and push it again so that it can successfully be merged

2025-02-23 19:42 UTC, Agaba-derrick commented
![Screenshot from 2025-02-23 22-26-16](https://github.com/user-attachments/assets/6a6744fc-5baa-4c70-8738-0234b6f454e2)

2025-02-24 10:43 UTC, mozzy11 commented
Thanks @Agaba-derrick

2025-02-24 10:50 UTC, merged