added a SampleHumanServicesTest class
I-TECH-UW/OpenELIS-Global-2 pull request #1311
Opened 2024-11-17 13:48 UTC by josephbate

# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Summary
added a SampleHumanServicesTest class
## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue

[Add a link to the related issue or mention it here if applicable]

## Other

[Add any additional information or notes here]

2024-11-17 18:35 UTC, mherman22 requested changes
LGTM if you fix the comment below

Thanks @josephbate

2024-11-17 18:35 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
The test class would benefit from using Java constants for test data values. Here's how you could refactor the repeated test data:

```java
private static final String PATIENT_FIRSTNAME = "John";
private static final String PATIENT_LASTNAME = "Doe";
private static final String PROVIDER_FIRSTNAME = "Jane";
private static final String PROVIDER_LASTNAME = "Loo";
private static final String PATIENT_BIRTHDATE = "03/06/1993";
private static final String SAMPLE_ACCESSION_NUMBER = "12345";
private static final String PATIENT_GENDER = "M";
private static final String SAMPLE_RECEIVED_TIMESTAMP = "012/06/2024";
private static final String PROVIDER_TYPE = "Physic";
private static final String SAMPLE_ENTERED_DATE = "2024-06-03";
```
Constants in Java, declared with `static final` and named in UPPERCASE_SNAKE_CASE, improve code maintainability, reduce typos, and follow the "Single Source of Truth" principle. They simplify mass updates, document magic values, and enable reuse across multiple test methods.

2024-11-19 07:44 UTC, josephbate commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
thank you @mherman22 for this insight let make these changes and comit

2024-11-20 05:58 UTC, mherman22 requested changes
@josephbate this looks good,

just a few minor suggestions below:

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        samp.setReceivedTimestamp(doc);
```suggestion
        samp.setReceivedTimestamp(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(SAMPLE_RECEIVED_TIMESTAMP).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        pat.setBirthDate(dob);
```suggestion
        pat.setBirthDate(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(PATIENT_BIRTHDATE).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        pat.setBirthDate(dob);
```suggestion
        pat.setBirthDate(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(birthdate).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        samp.setReceivedTimestamp(doc);
```suggestion
        samp.setReceivedTimestamp(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(receivedTimestamp).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        pat.setBirthDate(dob);
```suggestion
        pat.setBirthDate(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(PATIENT_BIRTHDATE).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        samp.setReceivedTimestamp(doc);
```suggestion
        samp.setReceivedTimestamp(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(SAMPLE_RECEIVED_TIMESTAMP).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        pat.setBirthDate(dob);
```suggestion
        pat.setBirthDate(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(PATIENT_BIRTHDATE).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        samp.setReceivedTimestamp(doc);
```suggestion
        samp.setReceivedTimestamp(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(SAMPLE_RECEIVED_TIMESTAMP).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        pat.setBirthDate(dob);
```suggestion
        pat.setBirthDate(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(PATIENT_BIRTHDATE).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        samp.setReceivedTimestamp(doc);
```suggestion
        samp.setReceivedTimestamp(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(SAMPLE_RECEIVED_TIMESTAMP).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        pat.setBirthDate(dob);
```suggestion
        pat.setBirthDate(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(PATIENT_BIRTHDATE).getTime()));
```

2024-11-20 05:58 UTC, mherman22 commented on src/test/java/org/openelisglobal/samplehuman/SampleHumanServiceTest.java
> +        samp.setReceivedTimestamp(doc);
```suggestion
        samp.setReceivedTimestamp(new Timestamp(new SimpleDateFormat("dd/MM/yyyy").parse(SAMPLE_RECEIVED_TIMESTAMP).getTime()));
```

2024-11-21 10:23 UTC, mherman22 approved these changes
Thanks @josephbate , LGTM

cc: @mozzy11

2024-12-16 09:43 UTC, closed without merging

2024-12-16 09:43 UTC, mozzy11 commented
Let me close this since it implemented here https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1312