add Tests for Adress Packge
I-TECH-UW/OpenELIS-Global-2 pull request #1316
Opened 2024-11-19 09:56 UTC by josephbate

# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Summary
Added more tests for address package
## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue

[Add a link to the related issue or mention it here if applicable]

## Other

[Add any additional information or notes here]

2024-11-19 15:11 UTC, mherman22 requested changes

2024-11-19 15:11 UTC, mherman22 commented on src/test/java/org/openelisglobal/address/AddressPartServiceTest.java
> +        savedPart.setPartName("upadtedName");
```suggestion
        savedPart.setPartName("updatedName");
```

2024-11-19 15:11 UTC, mherman22 commented on src/test/java/org/openelisglobal/address/AddressPartServiceTest.java
> +        Assert.assertEquals("upadtedName", savedPart.getPartName());
```suggestion
        Assert.assertEquals("updatedName", savedPart.getPartName());
```

2024-11-19 15:11 UTC, mherman22 commented on src/test/java/org/openelisglobal/address/AddressPartServiceTest.java
> +        savedPart.setPartName("upadtedName");
```suggestion
        savedPart.setPartName("updatedName");
```

2024-11-19 15:11 UTC, mherman22 commented on src/test/java/org/openelisglobal/address/AddressPartServiceTest.java
> +        savedPart.setPartName("upadtedName");
Why are you setting a new name here? shouldn't you just delete?

2024-11-19 15:11 UTC, mherman22 commented on src/test/java/org/openelisglobal/address/PersonAdressServiceTest.java
> +        AddressPK savedPAID = pAddressService.insert(personAddress);
```suggestion
        AddressPK savedAddressPK = pAddressService.insert(personAddress);
```

2024-11-19 15:14 UTC, mherman22 commented
can you close https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1312 if you nolonger need it?

2024-11-19 20:46 UTC, mozzy11 commented
Thanks @mherman22 .
@josephbate can you look at the above comments ??

2024-11-21 10:26 UTC, mherman22 approved these changes
LGTM, thanks @josephbate

2024-11-21 10:33 UTC, josephbate commented
> LGTM, thanks @josephbate

thank you too

2024-12-20 01:51 UTC, closed without merging