removed the single submenus as per issue:OGC-17
I-TECH-UW/OpenELIS-Global-2 pull request #1354
Opened 2024-12-21 11:36 UTC by vsvishalsharma

# Pull Request Requirements

- [x] The PR title includes a brief description of the work done, including the Issue number if applicable.
- [x] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes conform to the OpenElis Global x3 Styleguide and design documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary

This PR resolves issue [OGC-17](https://uwdigi.atlassian.net/jira/software/c/projects/OGC/issues/OGC-17?filter=allissues&jql=project%20%3D%20%22OGC%22%20AND%20status%20%3D%20%22Community%20To%20Do%22%20ORDER%20BY%20created%20DESC)  by improving the navigation menu functionality. It ensures that if a menu has only one submenu, the submenu is replaced with a direct link, using the parent menu's name as the navigation label. This enhancement simplifies user interaction by reducing unnecessary nesting in the navigation structure.

## Screenshots

*Before: Submenu
![Screenshot from 2024-12-20 23-04-53](https://github.com/user-attachments/assets/da93353f-8a86-4971-a5b0-e7f2de1467e7)
s were displayed even when there was only one submenu.*

!
*After: Direct link is shown for menus with a single submenu.*
![Screenshot from 2024-12-21 16-47-13](https://github.com/user-attachments/assets/e616bc45-245c-41ec-85f5-6b96fd60caff)

## Related Issue

OGC-17](https://uwdigi.atlassian.net/jira/software/c/projects/OGC/issues/OGC-17?filter=allissues&jql=project%20%3D%20%22OGC%22%20AND%20status%20%3D%20%22Community%20To%20Do%22%20ORDER%20BY%20created%20DESC)

2024-12-21 11:47 UTC, vsvishalsharma commented
## All the nav links are working as expected 

[Screencast from 21-12-24 05:15:14 PM IST.webm](https://github.com/user-attachments/assets/0ff98f15-ccb3-4d8e-a4e0-284fe1fc1c8c)

2024-12-24 13:44 UTC, Bahati308 reviewed
hello @vsvishalsharma , did you run this command **cd frontend** and then **npm run format** ??

2024-12-24 14:57 UTC, vsvishalsharma commented
@Bahati308 thanks for mentioning it !

2024-12-24 15:22 UTC, vsvishalsharma commented
@mozzy11  i need your feedback on 

## Issue: Current test flows expect dropdown navigation for Pathology/Immunochemistry menus, but we simplified UX for single-submenu cases to use direct links. This breaks existing tests.
### impact:
`#menu_pathology_dropdown` clicks failing in cypress test for `dashboard.cy.js`
Status selection errors
Similar issues in Immunochemistry flow

## Options:
Update test flows to match new UX
Revert to dropdown pattern with auto-expansion

I can implement either solution and am willing to consider any other approach based on your feedback!

2024-12-24 17:27 UTC, adityadeshlahre commented
> @caseyi ,@mozzy11 i need your feedback on
> 
> ## Issue:
> Current test flows expect dropdown navigation for Pathology/Immunochemistry menus, but we simplified UX for single-submenu cases to use direct links. This breaks existing tests.
> 
> ### impact:
> `#menu_pathology_dropdown` clicks failing in cypress test for `dashboard.cy.js` Status selection errors Similar issues in Immunochemistry flow
> 
> ## Options:
> Update test flows to match new UX Revert to dropdown pattern with auto-expansion
> 
> I can implement either solution and am willing to consider any other approach based on your feedback!

@vsvishalsharma Option 1 is definitely a way to go just modify dashboard.cy.js file and test it locally and make sure the test is passing locally on a fresh instance.

2024-12-24 17:34 UTC, adityadeshlahre commented on frontend/src/components/layout/search/searchBar.css
can you uncommit this file ?? same for index.css and searchBar.js

2024-12-24 18:55 UTC, Bahati308 commented
> @Bahati308 thanks for mentioning it !

welcome. Did you run it, you need to pass the checks locally. In case of any challenge, reach out

2024-12-25 06:34 UTC, vsvishalsharma commented on frontend/src/components/layout/search/searchBar.css
Hey! Done

2025-01-02 17:48 UTC, vsvishalsharma commented
@adityadeshlahre if possible can you run the ci on this

2025-01-05 18:41 UTC, adityadeshlahre commented
> @adityadeshlahre if possible can you run the ci on this

![image](https://github.com/user-attachments/assets/bb640d6e-1363-4a1b-9f00-294aad7d4a45)

seems like all cypress tests are passing at least in headless mode :slightly_smiling_face:

2025-01-11 09:18 UTC, vsvishalsharma commented
@mozzy11 would like you review here

2025-01-16 12:46 UTC, mozzy11 commented
Thanks @vsvishalsharma . 
I have tested this and it works , but i think the more consistent aproach is to update the menu entry for[ pathology](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/resources/liquibase/2.8.x.x/menu.xml#L102-L129) , [cytology](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/resources/liquibase/2.8.x.x/menu.xml#L160-L187) and [Immunohistochemistry](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/resources/liquibase/2.8.x.x/menu.xml#L131-L158) using Liquibase so that we can keep a consistent behaviour of the menu items both on the old and new UI

You write a new Liquibase changeset to remove the submenu elements ie [menu_pathologydashboard ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/resources/liquibase/2.8.x.x/menu.xml#L121) , [menu_cytologydashboard](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/resources/liquibase/2.8.x.x/menu.xml#L179) , and [menu_immunochemdashboard ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/resources/liquibase/2.8.x.x/menu.xml#L150) and update the parent items to have an action URL.
That way , we wont need the changes in the UI Logic

2025-01-16 12:56 UTC, mozzy11 requested changes
Lest instead update the backend menu items with Liquibase instead of having to change the UI logic

2025-01-21 07:26 UTC, mozzy11 approved these changes

2025-01-21 07:26 UTC, mozzy11 commented
Thanks @vsvishalsharma

2025-01-21 07:26 UTC, merged