Add Roles By Lab Unit
I-TECH-UW/OpenELIS-Global-2 pull request #313
Opened 2022-02-16 17:11 UTC by mozzy11

2022-02-24 20:08 UTC, mozzy11 commented
![image](https://user-images.githubusercontent.com/29783151/155599570-9c14deb8-6e81-45a3-a31a-635b9d51ddb5.png)

2022-02-24 20:09 UTC, mozzy11 commented
![image](https://user-images.githubusercontent.com/29783151/155599640-ce128779-af27-4466-bc41-6ec37af6bc40.png)

2022-03-01 00:08 UTC, CalebSLane requested changes
DB ID's should be generated by using the corresponding sequence, and not hardcoded in the code or in liquibase. Can these ids be grabbed by name from the db instead please?

2022-03-01 23:29 UTC, CalebSLane approved these changes

2022-03-01 23:29 UTC, merged