test:Implement Reporting Range
I-TECH-UW/OpenELIS-Global-2 pull request #314
Opened 2022-02-22 13:45 UTC by gitcliff

Implement "Reporting Range"

2022-03-09 14:54 UTC, gitcliff commented
![Screenshot from 2022-03-09 09-46-07](https://user-images.githubusercontent.com/46714226/157466671-2f8cfd32-8789-4077-ba60-918c31a62243.png)
![Screenshot from 2022-03-09 09-19-03](https://user-images.githubusercontent.com/46714226/157466679-2724d5ab-0dec-4ef0-9294-82bd28a009cd.png)
![Screenshot from 2022-03-08 17-51-25](https://user-images.githubusercontent.com/46714226/157466683-3f3618b7-8137-40fb-afb5-dfed4a744337.png)
![Screenshot from 2022-03-08 17-50-32](https://user-images.githubusercontent.com/46714226/157466690-ed8c350b-293c-46ce-96d3-5a462c37869b.png)

2022-03-09 18:23 UTC, caseyi commented
@CalebSLane Please review this PR

2022-03-09 23:36 UTC, CalebSLane requested changes
can the added columns be implemented in liquibase (under src/main/resources/liquibase/2.6.x.x/...) instead of in the initDB scripts? Otherwise existing installations will miss out on these columns as those are only run on install the first time.

In ResultLimitBean.java, setValidRange has the same functionality of setReportingRange. Is this intentional? I see that TestModifyEntryController.java calls setValidRange twice in a row. I'm assuming that one is supposed to be setValidReportingRange?

2022-03-10 19:13 UTC, CalebSLane approved these changes

2022-03-10 19:17 UTC, merged