Test Validation Screen
I-TECH-UW/OpenELIS-Global-2 pull request #321
Opened 2022-03-22 09:46 UTC by gitcliff

Test Validation Screen

2022-03-22 09:47 UTC, gitcliff commented
![Screenshot from 2022-03-22 12-41-57](https://user-images.githubusercontent.com/46714226/159452849-e7efb02b-c01f-41f0-98c4-c3ef9a3de2f3.png)
![Screenshot from 2022-03-22 12-41-48](https://user-images.githubusercontent.com/46714226/159452855-08f485cc-716c-457d-96d4-1fbe8c4e906d.png)

2022-03-22 19:43 UTC, CalebSLane requested changes
@gitcliff as it is now, this checkbox is checking everything on the page. I believe that it is only supposed to check the objects that belong to the same order.

2022-03-22 19:44 UTC, CalebSLane commented
![image](https://user-images.githubusercontent.com/10550869/159562940-ac1f2f1c-3e24-48ab-9dbe-c411b2598fa9.png)
 The second order (and the "select all" checkbox should not be selected)

2022-03-24 21:24 UTC, CalebSLane approved these changes

2022-03-24 21:29 UTC, merged