Improved VL study forms and reports and fixed some bugs
I-TECH-UW/OpenELIS-Global-2 pull request #451
Opened 2023-05-11 09:45 UTC by Pkom17

2023-05-12 17:44 UTC, CalebSLane requested changes

2023-05-12 17:44 UTC, CalebSLane commented on src/main/java/org/openelisglobal/image/service/ImageServiceImpl.java
If we are going to catch the generic exception, we should do a LogEvent.LogErrorStack to make sure we can trace the error if it happens

2023-05-12 17:44 UTC, CalebSLane commented on src/main/resources/static/scripts/entryByProjectUtils.js
what is the value 1251 supposed to be? if it's an id is it going to be static across all instances? if not, can it be declared as a named variable to give it more context?

2023-05-12 17:44 UTC, CalebSLane commented on src/main/resources/static/scripts/neon/entryByProjectUtils.js
what is the value 1251 supposed to be? if it's an id is it going to be static across all instances? if not, can it be declared as a named variable to give it more context?

2023-05-12 17:44 UTC, CalebSLane commented on src/main/java/org/openelisglobal/patient/controller/BasePatientEntryByProject.java
what is distinct about genders_2 from genders?

2023-05-15 09:26 UTC, Pkom17 commented on src/main/java/org/openelisglobal/image/service/ImageServiceImpl.java
Okay... LogEvent has been added

2023-05-15 09:30 UTC, Pkom17 commented on src/main/resources/static/scripts/entryByProjectUtils.js
1251 is the dictionary ID for "No" response  in the dictionary table and it is supposed to be static accross instances. 
it is used here to check "No" response by default in the study forms

2023-05-15 09:30 UTC, Pkom17 commented on src/main/resources/static/scripts/neon/entryByProjectUtils.js
1251 is the dictionary ID for "No" response  in the dictionary table and it is supposed to be static accross instances. 
it is used here to check "No" response by default in the study forms

2023-05-15 10:11 UTC, Pkom17 commented on src/main/java/org/openelisglobal/patient/controller/BasePatientEntryByProject.java
the genders_2 is the same structure used for gender field in the others forms. As this method is used only in study patient update, it should be the same structure as the Patient or Study form entry gender fied. 
genders used in this method used raw field in the gender table and genders_2 use localization

2023-05-15 10:13 UTC, Pkom17 commented on src/main/java/org/openelisglobal/patient/controller/BasePatientEntryByProject.java
finally commented out the first one as it is not used elsewhere.

2023-05-22 22:47 UTC, CalebSLane approved these changes

2023-05-22 22:49 UTC, merged