Guiding text added to select element in TestSelectForm.js
I-TECH-UW/OpenELIS-Global-2 pull request #739
Opened 2024-03-01 20:59 UTC by PR4NJ41

Resolves Issue #738 

### Before
![Screenshot from 2024-03-02 01-50-16](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/7a944404-a6e5-4dbf-8eba-b10c7e89fb96)

### After
![Screenshot from 2024-03-02 01-48-27](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/3ae28d9c-eed7-449b-99e2-6c4c9e662722)

2024-03-02 09:19 UTC, rahul6603 commented
Hi @PR4NJ41 , I have worked on Workplan by test in the PR https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/655 , and I suggest having consistent logic across all pages (similar work was done in PRs https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/656 and https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/665). I have proposed a simpler change in a reviewed comment.

2024-03-02 09:21 UTC, rahul6603 commented on frontend/src/components/workplan/TestSelectForm.js
> -      let testLabel = test ? test.value : "";
Can we just change the testLabel here to `testLabel = test ? test.value : "Select Test Type"`

2024-03-03 20:01 UTC, PR4NJ41 commented on frontend/src/components/workplan/TestSelectForm.js
> -      let testLabel = test ? test.value : "";
@rahul6603 Thanks for reviewing my PR, I have made the required changes.

2024-03-05 21:27 UTC, CalebSLane requested changes
Text should use the internationalization functionality available by using intl.formatMessage({}), providing a message key, and placing the english value in en.json. We also support French (fr.json), but that can be added independently of this commit.

2024-03-07 09:10 UTC, codewithunknown commented
Amazing

2024-03-21 06:08 UTC, mozzy11 commented
> Text should use the internationalization functionality available by using intl.formatMessage({}), providing a message key, and placing the english value in en.json. We also support French (fr.json), but that can be added independently of this commit.

@PR4NJ41 can you resoleve the merge conflicts and also adrees the above comment ??

2024-03-21 12:14 UTC, merged