Added placeholder text to SearchPatientForm.js
I-TECH-UW/OpenELIS-Global-2 pull request #743
Opened 2024-03-03 23:14 UTC by PR4NJ41

Resolves Issue #738  
### Before
![Screenshot from 2024-03-04 04-41-08](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/5794902a-b707-4216-9ec0-ae27279a46b5)

### After
![Screenshot from 2024-03-04 04-40-08](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/4d3d1a31-734b-4f13-8568-fbcd7193e984)

2024-03-04 07:09 UTC, sherrif10 approved these changes
Looks good. Thanks @PR4NJ41

2024-03-05 21:10 UTC, CalebSLane requested changes
Text should use the internationalization functionality available by using intl.formatMessage({}), providing a message key, and placing the english value in en.json. We also support French (fr.json), but that can be added independently of this commit.

2024-03-21 06:05 UTC, mozzy11 commented
@PR4NJ41 did you see @CalebSLane's request above ??

2024-03-21 11:25 UTC, mozzy11 approved these changes

2024-03-21 11:25 UTC, merged