Rewritten Export Routine CSV report in the new Rect UI
I-TECH-UW/OpenELIS-Global-2 pull request #766
Opened 2024-03-07 11:08 UTC by konavivekramakrishna

This pr adds the Export Routine CSV report page

fixes : #762 

Before:
![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/101407963/7e5ea83a-56e8-41df-8967-8b8ddf6590e1)

After:
![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/101407963/05759530-2099-4847-ace7-2167856d37a9)

2024-03-08 01:30 UTC, mozzy11 commented
Thanks @konavivekramakrishna , 
Basically menu items are added using liquibase changesets to the DB ie [here](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/src/main/resources/liquibase/2.8.x.x/menu.xml#L102-L129) to I order to be compatible with the old jsp UI .,so we have the a single source of  menu items for both the new and old UI

2024-03-08 01:31 UTC, mozzy11 commented
Which menu item did you need to add ??

2024-03-08 02:26 UTC, mozzy11 requested changes
see above comments

2024-03-08 06:35 UTC, mozzy11 commented
actually, use the 
config.serverBaseUrl + "/RoutineReport?type=patient&report=referredOut"
i renamed it so that all new RoutineReports in the Rect UI can use that 
https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/frontend/src/App.js#L382

2024-03-08 06:39 UTC, konavivekramakrishna commented
Okay @mozzy11 

I have another recommendation for the frontend code. How about using Husky as a pre-commit hook to automatically format the frontend code using Prettier? This way, the code remains consistent, and the formatting will be consistent as well. What do you think about it?

Can I create a separate PR for the adding pre commit hook to auto format using prettier?

2024-03-08 07:12 UTC, konavivekramakrishna commented
@mozzy11 

I have implemented the changes and attached the screenshot could you please review

2024-03-10 21:03 UTC, mherman22 requested changes

2024-03-10 21:03 UTC, mherman22 commented on frontend/src/components/Reports/Routine.js
> +          link:"/RoutineReport?type=patient&report=referredOut",
i expected your changes to be about the Export Routine CSV but this change here says otherwise!

2024-03-10 21:03 UTC, mherman22 commented on frontend/src/components/Reports/Routine.js
> +          link:"/RoutineReport?type=patient&report=referredOut",
i expected your change to be around `/Report?type=patient&report=CISampleRoutineExport"` which can be found at https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/581e2fdfa93911db7d7c2dd04ae493dcdc54cab7/frontend/src/components/Reports/Routine.js#L133-L144 and not the above

2024-03-10 21:03 UTC, mherman22 commented on frontend/src/components/Reports/routine/ReferedOutTestSummary.js
i would probably go ahead and name my file as `CISampleRoutineExport.js`

2024-03-11 02:38 UTC, vivramkrishna commented on frontend/src/components/Reports/Routine.js
> +          link:"/RoutineReport?type=patient&report=referredOut",
Hey @mherman22 

Thanks, but if you see what @mozzy11  has suggested is to name the route as 
`/RoutineReport?type=patient&report=referredOut`

2024-03-11 02:39 UTC, vivramkrishna commented on frontend/src/components/Reports/routine/ReferedOutTestSummary.js
Sounds good

I will rename it👍
Thanks

2024-03-11 06:51 UTC, mherman22 commented on frontend/src/components/Reports/Routine.js
> +          link:"/RoutineReport?type=patient&report=referredOut",
as you can see this `/RoutineReport?type=patient&report=referredOut` is for the referredOut yet this pull request is supposed to address something about ExportRoutineCSV report.

2024-03-18 10:33 UTC, konavivekramakrishna commented
@mozzy11 

can you please review

2024-03-18 12:45 UTC, mozzy11 commented on frontend/src/components/Reports/Routine.js
> +          link:"/RoutineReport?type=patient&report=referredOut",
@konavivekramakrishna , 
@mherman22 is right . you worked on the wrong report menu item . 
YOu were supposed to work on [this ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/frontend/src/components/Reports/Routine.js#L133-L144)  ie it shoulb become 
`"/RoutineReport?type=patient&report=CISampleRoutineExport",`

2024-03-18 12:46 UTC, mozzy11 commented on frontend/src/components/Reports/routine/Index.js
> +                report === "referredOut" &&
the reort is supposed to be `CISampleRoutineExport`

2024-03-18 12:48 UTC, mozzy11 requested changes
Use the right report menu item

2024-03-19 11:42 UTC, closed without merging