[fix]: failing test
I-TECH-UW/OpenELIS-Global-2 pull request #815
Opened 2024-03-15 19:10 UTC by valens200

Fixed the failing test which was failing all the times.

Initially, this test expects to receive several patients equal to one but in real implementation, the output of `"patientService.getAllPatients().size()"` is zero which leads to the failure of the test.

<img width="633" alt="Screen Shot 2024-03-15 at 21 07 48" src="https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/95166477/2d35a839-63ed-431a-8e1f-73fdff876c37">

The test was modified by replacing `1` with `0`.

<img width="665" alt="Screen Shot 2024-03-15 at 21 07 39" src="https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/95166477/af8e3eda-1836-4971-bf7e-eee8ac7bf265">

2024-03-16 04:47 UTC, valens200 commented
@mozzy11  @reagan-meant you can review this PR and suggest changes. 
Thank you.

2024-03-18 10:49 UTC, mozzy11 commented on volume/tomcat/hapi_server.xml
> -<Server port="-1" shutdown="SHUTDOWN">
get rid of these changes , its probably updated the by the container volume.

2024-03-18 19:12 UTC, mozzy11 commented
Thanks @valens200 , 
did your tests pass locally ??

2024-03-18 20:01 UTC, valens200 commented
Yes @mozzy11, I think the action build is failing due to changing this port as you requested.
<img width="600" alt="Screen Shot 2024-03-18 at 21 57 53" src="https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/95166477/2184657d-78de-48c6-912f-fd71bb6e8dd0">

Setting it to -1 makes the tests to failure because the data source can't be found.

2024-03-18 20:05 UTC, valens200 commented
> Thanks @valens200 , did your tests pass locally ??



> @mozzy11 @reagan-meant you can review this PR and suggest changes. Thank you.

yes

2024-03-19 06:51 UTC, mozzy11 commented
@valens200 i dont think thats right , 
These are integration tests at the service layer and they dont have any thing to do with the servlet container .

2024-03-19 06:57 UTC, mozzy11 commented on src/test/java/org/openelisglobal/patient/PatientServiceTest.java
> +		String patientId = patientService.insert(pat);
can you assert the patient exists before delete ?

2024-03-19 06:58 UTC, mozzy11 commented on volume/tomcat/hapi_server.xml
> -<Server port="-1" shutdown="SHUTDOWN">
we dont need these changes here for the tests to pass

2024-03-19 06:59 UTC, mozzy11 requested changes
Get rid of the server,xml changes and also add an assertion before delete

2024-03-19 09:38 UTC, valens200 commented
I see @mozzy11 , let me apply the changes

2024-03-19 09:39 UTC, valens200 commented
> @valens200 i dont think thats right , These are integration tests at the service layer and they dont have any thing to do with the servlet container .

Yes sir @mozzy11

2024-03-19 16:26 UTC, valens200 commented
@mozzy11 I think that's all.

2024-03-21 04:02 UTC, valens200 commented
@mozzy11 you can check for changes.

2024-03-21 05:41 UTC, mozzy11 requested changes
Thanks @valens200 . 
you still have format changes in hapi_server.xml file . 
amd also can you also put the Guide changes in a separate PR ??

2024-03-22 11:57 UTC, valens200 commented
@mozzy11 If you are here please you can see re-review this.

2024-03-25 10:01 UTC, closed without merging