Adding pull request requirements to the readme.md
I-TECH-UW/OpenELIS-Global-2 pull request #829
Opened 2024-03-18 22:33 UTC by Agaba-derrick

fixes https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/827

2024-03-19 06:46 UTC, mozzy11 requested changes
Thanks @Agaba-derrick . 
For a pull request template 
see [instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

ie create a file called ` .github/PULL_REQUEST_TEMPLATE.md`
and add the requirements so that the requirement appear by default in each PR created. 

see example here  https://github.com/google/fhir-data-pipes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2024-03-20 10:12 UTC, mozzy11 commented on README.md
>  # OpenELIS Global 2
Can you get rid of the format changes in the Read me , i dont see any actual change

2024-03-20 19:05 UTC, mozzy11 requested changes
@Agaba-derrick , can you get rid of the  format changes in the read me file ??

2024-03-21 04:51 UTC, Agaba-derrick commented
> @Agaba-derrick , can you get rid of the format changes in the read me file ??

sure amon it now

2024-03-21 11:32 UTC, mozzy11 approved these changes

2024-03-21 11:32 UTC, mozzy11 approved these changes

2024-03-21 11:35 UTC, merged