Add e2e jobs for Chrome and firefox browsers
I-TECH-UW/OpenELIS-Global-2 pull request #859
Opened 2024-03-22 04:59 UTC by tendomart

# Pull Requests Requirements

## Summary
Add e2e jobs for Chrome and firefox browsers 

These run the default inbuilt cypress browser, chrome and Firefox.

Should be triggered on push

https://github.com/tendomart/OpenELIS-Global-2/commit/2251652afe9df022a6d317e2f81e94a1d5e581f6

Hi @mozzy11  should focus on this commit 
https://github.com/tendomart/OpenELIS-Global-2/commit/2251652afe9df022a6d317e2f81e94a1d5e581f6

2024-03-25 04:55 UTC, Ankit-Matth requested changes
Hey @tendomart, I believe some unnecessary changes were accidentally included in this PR from previous commits. Could you please take a look at it?

2024-03-25 04:55 UTC, Ankit-Matth commented on frontend/src/components/admin/Admin.js
Are changes to this file necessary for adding end-to-end (e2e) jobs for Chrome and Firefox browsers? I think these came by mistake from a previous commit.

2024-03-25 04:55 UTC, Ankit-Matth commented on frontend/src/components/common/GenericBreadCrumb.js
Are changes to this file necessary for adding end-to-end (e2e) jobs for Chrome and Firefox browsers? I think these came by mistake from a previous commit.

2024-03-25 04:55 UTC, Ankit-Matth commented on frontend/src/components/validation/Index.js
Are changes to this file necessary for adding end-to-end (e2e) jobs for Chrome and Firefox browsers? I think these came by mistake from a previous commit.

2024-03-26 06:50 UTC, mozzy11 requested changes
@tendomart Thanks for working on this. 
I think you have changes that are not needed in this PR

2024-03-26 07:23 UTC, tendomart commented
Yes thanks, @mozzy11 , I thought you would selectively pick the last commit. but will remove them sometime today.

2024-06-10 08:08 UTC, mozzy11 commented
THanks @tendomart can you adress the CI Build failre and merge conflicts ?

2024-06-10 08:18 UTC, tendomart commented
Alright @mozzy11  will find some time later today and look into resolving this

2024-08-01 07:30 UTC, closed without merging