Fix Duplicate National Id/Subject No. persistence
I-TECH-UW/OpenELIS-Global-2 pull request #909
Opened 2024-03-26 12:48 UTC by common-cold

# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the Issue number if applicable.
- [x] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes confirm to the OpenElis Global x3 Styleguide and design documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary
fixes: [#788 ](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/788)

The current validator named **validatePatientInfo()** in **PatientServiceRestController** class is not properly handling this issue. It only focusses on the duplicate SubjectNumber's value. 

While setting  
- duplicate Subject Number = false , and
- duplicate National ID = true

I try to save a new patient with new Subject Number and a duplicate national ID I get an error while persisting this patient. This happens due to incomplete execution of **preparePatientData()** in **PatientManagementRestController** class. This further leads to an error from hibernate saying "attempt to create saveOrUpdate event from null entity". Which should not happen.  

This pull request adds a new validator named **validatePatientInfo()** in **persistPatientData()** inside **PatientServiceImpl** class, and sets the response status to 400 when the validator fails.
This new validator is taking account both subject Number and National ID. And works for all permutations for TRUE/FALSE.

## Screenshots

1. 

![Screenshot 2024-03-24 041500](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/30d21bc0-25c1-45a6-925f-00c2b55b3dd5)
![Screenshot 2024-03-24 041607](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/5db1e2d1-9e69-40f5-85b6-f6852beb9ee9)
![Screenshot 2024-03-24 041623](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/71c332e5-baa0-4da7-bcc0-99756ded35da)

2.
![Screenshot 2024-03-24 041739](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/a2543294-1e49-440d-950a-9478dbf3f665)
![Screenshot 2024-03-24 041919](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/b1ad34d5-c6a6-4f27-8c2a-15713c5972d9)
![Screenshot 2024-03-24 042005](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/570b1081-3a4f-4067-a55c-e9dff45e9716)

3.
![Screenshot 2024-03-24 042049](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/793ccacf-44e6-4f91-bcc7-8e7de7d9e596)
![Screenshot 2024-03-24 042339](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/3c15d21b-56ae-490a-80c8-78cc2d2045e7)
![Screenshot 2024-03-24 042424](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/74721b27-892a-4204-a158-809cf6c699a5)
![Screenshot 2024-03-24 042516](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/115c984a-8954-437f-97b2-57e6d63b5e3b)

4.
![Screenshot 2024-03-24 042645](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/4af7521f-d942-478c-b98a-afc8f3362a28)
![Screenshot 2024-03-24 042820](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/7f96924a-1a55-4384-a6b7-57a1c68b2a6e)

## Other
The current validator is not properly validating the conditions. And also focusses on subjectNumber parameter only. 
GIven that the new validator is working fine I suggest we can replace the old validator from the new validator entirely.

2024-03-26 15:46 UTC, mozzy11 commented on src/main/java/org/openelisglobal/patient/service/PatientServiceImpl.java
> +    private Errors validatePatientInfo(PatientManagementInfo patientInfo) {
Why dont you just add this validation function in the controller wherw it was before ??

2024-03-26 15:47 UTC, mozzy11 commented on src/main/java/org/openelisglobal/patient/controller/rest/PatientManagementRestController.java
> +//        validatePatientInfo(errors, patientInfo);
can you just update this function to catch duplicate IDs ?

2024-03-26 15:48 UTC, mozzy11 requested changes
I think move the validation function back to the controller , it will also fix the CI build

2024-03-26 17:32 UTC, common-cold commented on src/main/java/org/openelisglobal/patient/controller/rest/PatientManagementRestController.java
> +//        validatePatientInfo(errors, patientInfo);
Alright I'll change that.

2024-03-29 19:24 UTC, common-cold commented
@mozzy I have commented out the old validator instead of deleting it completely. Let me know if you want it to be removed

2024-03-30 12:14 UTC, common-cold commented
@mozzy11 please review this

2024-04-03 16:43 UTC, common-cold commented
@mozzy11 any feedback on why the frontend framework is failing?

2024-04-12 01:49 UTC, mozzy11 commented on src/main/java/org/openelisglobal/patient/controller/rest/PatientManagementRestController.java
> +    private void validatePatientInfo(Errors errors, PatientManagementInfo patientInfo) {
Thanks @common-cold , can you just update the existing functionality rather than commenting it out ??

2024-04-12 01:51 UTC, mozzy11 requested changes
you can  just refactor and update the existing function rather than commenting it out and creating another

2024-04-12 12:00 UTC, common-cold commented
@mozzy11 I have done the changes

2024-04-14 05:35 UTC, mozzy11 approved these changes

2024-04-14 05:37 UTC, merged