Re-write Export by Date Report
I-TECH-UW/OpenELIS-Global-2 pull request #912
Opened 2024-03-26 18:30 UTC by konavivekramakrishna

# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the Issue number if applicable.
- [x] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes confirm to the OpenElis Global x3 Styleguide and design documentation.
- [ ] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Screenshots

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/101407963/90675b48-6de9-4f05-a756-33bd4af4cb0f

## Related Issue

fixes : #895 

This pr adds new page for of study reports: Export by Date Report and moved encodeDate function into utils

2024-03-27 03:32 UTC, mozzy11 commented on frontend/src/components/reports/study/common/ReportByDateCSV.js
> +          {
The Project codes are suppsoed to be pulled from the backend ie see [here](https://github.com/mozzy11/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/reports/action/implementation/ExportProjectByDate.java#L205-L219)

Youll build an end point of in the [DisplayListController](https://github.com/mozzy11/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/common/rest/DisplayListController.java) that returns the List<IdValuePair>  for the the Project code and  Project Id of these [projects](https://github.com/mozzy11/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/reports/action/implementation/ExportProjectByDate.java#L205-L219) .  see [example ](https://github.com/mozzy11/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/common/rest/DisplayListController.java#L376)

2024-03-27 03:34 UTC, mozzy11 commented on frontend/src/components/reports/study/common/ReportByDateCSV.js
> +          {
Same for thse Poject codes , this is the List of [Projects](https://github.com/mozzy11/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/reports/action/implementation/ExportTrendsByDate.java#L238-L263)

2024-03-27 03:36 UTC, mozzy11 requested changes
The project codes should be pulled from the resnt endpoind

2024-04-03 11:01 UTC, konavivekramakrishna commented
@mozzy11 

can you please review

2024-04-03 12:22 UTC, konavivekramakrishna commented
@mozzy11 

can you please review it


https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/101407963/13b62712-82a0-416d-a52f-0301d8489739

2024-04-03 12:51 UTC, mozzy11 approved these changes

2024-04-03 12:52 UTC, mozzy11 commented on src/main/java/org/openelisglobal/common/rest/DisplayListController.java
> +  	@GetMapping(value = "trendsprojects", produces = MediaType.APPLICATION_JSON_VALUE)
improper code formating

2024-04-03 12:53 UTC, mozzy11 commented on src/main/java/org/openelisglobal/common/rest/DisplayListController.java
> +	@Autowired
improper formating

2024-04-03 12:53 UTC, mozzy11 commented
Thanks @konavivekramakrishna

2024-04-03 12:54 UTC, merged