Add more integration tests to the Patient and Person service #902
I-TECH-UW/OpenELIS-Global-2 pull request #929
Opened 2024-03-28 15:47 UTC by josephbate

2024-03-28 16:11 UTC, mherman22 requested changes

2024-03-28 16:11 UTC, mherman22 commented on src/test/java/org/openelisglobal/person/PersonServiceTest.java
> +
correct indention of this entire file.

2024-03-28 17:50 UTC, josephbate commented on src/test/java/org/openelisglobal/person/PersonServiceTest.java
> +
oh okay

2024-03-29 09:05 UTC, EdisonMeks commented on src/test/java/org/openelisglobal/person/PersonServiceTest.java
> +
Do we need all these white spaces

2024-03-31 06:24 UTC, josephbate commented on src/test/java/org/openelisglobal/person/PersonServiceTest.java
> +
am fix  it

2024-04-09 11:51 UTC, closed without merging