worked on writing the nonconformity notification in the new react ui
I-TECH-UW/OpenELIS-Global-2 pull request #933
Opened 2024-03-29 01:14 UTC by EdisonMeks

# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Summary
I created a new component for the the nonconformity notification in the new react ui
## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue

[[Add a link to the related issue or mention it here if applicable]](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/896)

## Other

[Add any additional information or notes here]

2024-03-29 01:24 UTC, EdisonMeks commented
please @mozzy11 you can review cc @sherrif10 @Agaba-derrick @reagan-meant

2024-03-29 05:51 UTC, mozzy11 commented
Thanks @EdisonMeks , 
Can you attch a screenshot or Screenrecording of your changes to help reviwers??

2024-03-29 07:47 UTC, EdisonMeks commented
ok, let me do the needful

2024-03-29 08:25 UTC, mozzy11 commented on frontend/src/App.js
> +                 <SecureRoute
You dint need another Route . theres already a `Route `path for Routine Reports

2024-03-29 13:43 UTC, EdisonMeks commented on frontend/src/App.js
> +                 <SecureRoute
ok

2024-03-31 18:13 UTC, EdisonMeks commented
@mozzy11 have added the required changes you can give a review

2024-04-01 11:28 UTC, mozzy11 commented on frontend/src/components/reports/study/NonconformityNotification.js
> +    { label: '', value: '' },
you need need to pull this from this endpoint `/rest/site-names`

2024-04-01 11:30 UTC, mozzy11 commented on frontend/src/components/reports/study/NonconformityNotification.js
> +    setLoading(true);
for submititng , just dynalically build a url with params like below and openit in a new tab ie 
/ReportPrint?report=retroCInonConformityNotification&type=patient&accessionDirect=<accesionNumber>&selectList.selection=<SiteId>

2024-04-01 11:32 UTC, mozzy11 commented on frontend/src/components/reports/study/NonconformityNotification.js
> +    setLoading(true);
see [example ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/frontend/src/components/reports/routine/ReferredOut.js#L90-L105)of how its done

2024-04-01 11:33 UTC, mozzy11 requested changes
see comments above . 
Also attach a screen recording

2024-04-09 09:27 UTC, mozzy11 commented
Thanks @EdisonMeks .
Any progress here or blocker ??

2024-04-15 22:11 UTC, mozzy11 commented
Thanks @EdisonMeks for attemting to work on this isse. 
We needed it urgently so it has been worked on in this PR https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/982.
Feel free to try out another issue

2024-04-15 22:11 UTC, closed without merging